### ISSUE TITLE
Delete Address is not working

### ISSUE THREAD

**Issue by bdheeman** [laanwj/bitcoin-qt#7]
Deletion of address is not working neither in the Sending nor Receiving tab of Address book dialogs (both selection of default receiving address and, or edit node)

**Comment by bdheeman** [comment]
Plz find some time to have a look at some patched available http://anu.homelinux.net/pub/patches/bitcoin-qt-git/ and feel free to apply/adapt/use any these changes I made.

**Comment by laanwj** [comment]
Deletion of addresses in the Receiving tab doesn't work (the "delete" button
will be disabled). This is the same in the Wx GUI and is because receiving
addresses

1) still might have coins in them

2) they might receive coins later on.

In the sending tab, deletion works for me (select an address, push the
delete button). I cannot reproduce the problem.

Does this happen for specific addresses or all of them? What OS?

**Comment by bdheeman** [comment]
I build and packaged bitcoin-qt for Debian GNU/Linux wheezy/testing, libqt4-dev 4.7.3, libboost-dev   1.46.1.1,  libdb4.8-dev and libdb4.8++-dev 4.8.30, that's what Debian wheezy has as latest versions.

Well accessing Address Book management from button-bar works perfectly or in-line with original/wx version, but the Delete button is/was enabled in Receiving tab when accessing address-book for setting/selecting default receiving address, which confused me that the deletion did not work in receiving tab :(

**Comment by laanwj** [comment]
Yup I can confirm that bug, thanks for reporting
